web:
  build: .
  links:
    - mongo
  ports:
    - 3000:3000
  volumes:
    - .:/app
    - /app/node_modules
  environment:
    JAMB_API_MONGODB_URI:  "mongodb://mongo:27017/jamb"
    NODE_ENV: production
mongo:
  image: mongo
  ports:
    - 27017:27017